export const initialState = {
  text: '',
  categories: [
    {
      name: 'Verbos',
      color: "#eaa134",
      words: [
        'abrir',
        'aprender',
        'beber',
        'buscar',
        'caminar',
        'cerrar',
        'cocinar',
        'comenzar',
        'comer',
        'conocer',
        'creer',
        'dar',
        'decir',
        'encontrar',
        'entender',
        'escribir',
        'estar',
        'haber',
        'hablar',
        'hacer',
        'ir',
        'jugar',
        'leer',
        'llamar',
        'llegar',
        'mirar',
        'necesitar',
        'pagar',
        'pedir',
        'pensar',
        'poder',
        'poner',
        'preferir',
        'quedar',
        'querer',
        'saber',
        'salir',
        'sentarse',
        'sentir',
        'ser',
        'tener',
        'tomar',
        'trabajar',
        'traer',
        'usar',
        'venir',
        'ver',
        'viajar',
        'vivir',
        'volver'
      ]
    },
    {
      name: 'Pronombres',
      color: '#8f4baa',
      words: [
        'yo',
        'tú',
        'él',
        'ella',
        'nosotros',
        'nosotras',
        'vosotros',
        'vosotras',
        'ellos',
        'ellas'
      ]
    }
  ]
}