import createStoreHook from 'zustand'
import createStore from 'zustand/vanilla'

export const store = createStore(
  () => ({
    wordCategories: {
      friends: {
        name: 'Amigos',
        color: '#0083f5'
      },
      verbs: {
        name: 'Verbos',
        color: '#e76f51'
      },
      pronouns: {
        name: 'Pronombres',
        color: '#8f4baa'
      },
      adverbs: {
        name: 'Adverbios',
        color: '#287271'
      }
    },
    wordsByCategoryId: {
      friends: [
        'Sílvia',
        'Mario',
        'Isa',
        'Mike',
        'Ricardo',
        'Jorge Abascal',
        'José',
        'Inma',
        'Julio',
        'Laura',
        'Ara',
        'Carolina',
        'Andrea',
        'Alexandra',
        'Álex',
        'El impecable',
        'Belén',
        'David',
        'Fran',
        'Marius'
      ],
      verbs: [
        'abrir',
        'aprender',
        'beber',
        'buscar',
        'caminar',
        'cerrar',
        'cocinar',
        'comenzar',
        'comer',
        'conocer',
        'creer',
        'dar',
        'decir',
        'encontrar',
        'entender',
        'escribir',
        'estar',
        'haber',
        'hablar',
        'hacer',
        'ir',
        'jugar',
        'leer',
        'llamar',
        'llegar',
        'mirar',
        'necesitar',
        'pagar',
        'pedir',
        'pensar',
        'poder',
        'poner',
        'preferir',
        'quedar',
        'querer',
        'saber',
        'salir',
        'sentarse',
        'sentir',
        'ser',
        'tener',
        'tomar',
        'trabajar',
        'traer',
        'usar',
        'venir',
        'ver',
        'viajar',
        'vivir',
        'volver'
      ],
      pronouns: [
        'yo',
        'tú',
        'él',
        'ella',
        'nosotros',
        'nosotras',
        'vosotros',
        'vosotras',
        'ellos',
        'ellas'
      ],
      adverbs: [
        'aquí',
        'cerca',
        'recién',
        'ya',
        'nunca',
        'posiblemente',
        'mal',
        'muy',
        'lejos',
        'no',
        'abajo',
        'ayer',
        'aún',
        'bien',
        'casi',
        'siempre',
        'hoy',
        'regular',
        'últimamente',
        'más',
        'encima',
        'acá',
        'arriba',
        'todavía',
        'mejor',
        'despacio',
        'algo',
        'mañana',
        'tarde',
        'fuera',
        'delante',
        'ahora',
        'mucho',
        'así',
        'detrás',
        'pronto',
        'temprano',
        'jamás',
        'dentro',
        'seguramente',
        'quién',
        'indudablemente',
        'poco',
        'probablemente',
        'peor',
        'tampoco',
        'bastante',
        'rápidamente',
        'sí',
        'similar',
        'harto',
        'fácilmente',
        'demasiado',
        'a lo mejor',
        'dónde',
        'cuándo',
        'cómo',
        'seguro',
        'ciertamente',
        'quizás',
        'qué',
        'acaso',
        'efectivamente',
        'tal vez',
        'ni siquiera',
        'verdaderamente'
      ]
    }
  })
)

export const useSelector = createStoreHook(store)
